apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arise-realtime
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arise-realtime
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
